const teste = [
  {
    COD: 'Cód. Produto',
    GTIN: 'Cód. GTIN',
  },
  {
    COD: '152770',
    GTIN: 'Não Informado',
  },
  {
    COD: '84716',
    GTIN: 'Não Informado',
  },
  {
    COD: '97642',
    GTIN: '7891999003072',
  },
  {
    COD: '98840',
    GTIN: '7891999003683',
  },
  {
    COD: '77592',
    GTIN: '7891021002127',
  },
  {
    COD: '118160',
    GTIN: '7898953148169',
  },
  {
    COD: '131586',
    GTIN: '7896089013634',
  },
  {
    COD: '149852',
    GTIN: '7892840818234',
  },
];

const products = [
  {
    '#': 1,
    COD: '49421',
    DESCRIÇÃO: 'REFRI COCA COLA VD 250ML',
    QTD: '6',
    UN: 'UN',
    VL_UN_R$: '2,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '17,94',
  },
  {
    '#': 2,
    COD: '97642',
    DESCRIÇÃO: 'CERVEJA CORONA EXTRA LN 330ML',
    QTD: '6',
    UN: 'UN',
    VL_UN_R$: '6,49',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '38,94',
  },
  {
    '#': 3,
    COD: '54985',
    DESCRIÇÃO: 'REFRI COCA COLA ZERO PET 200ML',
    QTD: '1',
    UN: 'FD',
    VL_UN_R$: '15,48',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '15,48',
  },
  {
    '#': 4,
    COD: '5961',
    DESCRIÇÃO: 'CERVEJA HEINEKEN LN 330ML',
    QTD: '6',
    UN: 'UN',
    VL_UN_R$: '5,45',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '32,70',
  },
  {
    '#': 5,
    COD: '118160',
    DESCRIÇÃO: 'CERVEJA HEINEKEN LTA 350ML',
    QTD: '12',
    UN: 'UN',
    VL_UN_R$: '4,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '59,88',
  },
  {
    '#': 6,
    COD: '2362',
    DESCRIÇÃO: 'QUEIJO ESTEPE TIROLEZ kg',
    QTD: '0,168',
    UN: 'KG',
    VL_UN_R$: '85,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '14,43',
  },
  {
    '#': 7,
    COD: '131586',
    DESCRIÇÃO: 'QUEIJO EMMENTAL VIGOR kg',
    QTD: '0,258',
    UN: 'KG',
    VL_UN_R$: '95,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '24,74',
  },
  {
    '#': 8,
    COD: '25442',
    DESCRIÇÃO: 'SMIRNOFF ICE 275ML',
    QTD: '5',
    UN: 'UN',
    VL_UN_R$: '8,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '44,50',
  },
  {
    '#': 9,
    COD: '57414',
    DESCRIÇÃO: 'CERVEJA HEINEKEN LN 330ML Z/ALCOOL',
    QTD: '2',
    UN: 'UN',
    VL_UN_R$: '5,49',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '10,98',
  },
  {
    '#': 10,
    COD: '45543',
    DESCRIÇÃO: 'SORVETE KIBON 1,5L NAPOLITANO',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '23,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '23,90',
  },
  {
    '#': 11,
    COD: '56774',
    DESCRIÇÃO: 'AMENDOIM ELMA CHIPS 400G OVINHO',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '13,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '13,99',
  },
  {
    '#': 12,
    COD: '9201',
    DESCRIÇÃO: 'AMENDOIM PETTIZ DORI CROCANTE 150G SALSA CEBOLA',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '6,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '6,99',
  },
  {
    '#': 13,
    COD: '6058',
    DESCRIÇÃO: 'LEITE COCO SOCOCO 200ML VD',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '4,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '4,99',
  },
  {
    '#': 14,
    COD: '6058',
    DESCRIÇÃO: 'LEITE COCO SOCOCO 200ML VD',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '4,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '4,99',
  },
  {
    '#': 15,
    COD: '6068',
    DESCRIÇÃO: 'LEITE COND MOCA 395G',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '6,49',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '6,49',
  },
  {
    '#': 16,
    COD: '6068',
    DESCRIÇÃO: 'LEITE COND MOCA 395G',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '6,49',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '6,49',
  },
  {
    '#': 17,
    COD: '15405',
    DESCRIÇÃO: 'COBERTURA INGREDIENT 240G CARAMELO',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '14,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '14,90',
  },
  {
    '#': 18,
    COD: '9387',
    DESCRIÇÃO: 'COBERTURA KENKO 250G CHOCOLATE',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '9,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '9,90',
  },
  {
    '#': 19,
    COD: '9213',
    DESCRIÇÃO: 'AZEITE OLIVA CARBONELL EX VIRGEM 500ML',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '21,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '21,99',
  },
  {
    '#': 20,
    COD: '36190',
    DESCRIÇÃO: 'AZEITONA RAIOLA VERDE DESCAROCADA 280G',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '18,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '18,90',
  },
  {
    '#': 21,
    COD: '59811',
    DESCRIÇÃO: 'FAROFA MANDIOCA YOKI PREMIUM 380G TRADICIONAL',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '9,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '9,99',
  },
  {
    '#': 22,
    COD: '9256',
    DESCRIÇÃO: 'ARROZ TIO JOAO TP1 1kg',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '5,49',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '5,49',
  },
  {
    '#': 23,
    COD: '30422',
    DESCRIÇÃO: 'ACUCAR CRISTAL ORG NATIVE 1kg',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '5,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '5,99',
  },
  {
    '#': 24,
    COD: '58143',
    DESCRIÇÃO: 'SUCO SUPERBOM 100 FRUTA 1L TANGERI',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '10,49',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '10,49',
  },
  {
    '#': 25,
    COD: '5961',
    DESCRIÇÃO: 'CERVEJA HEINEKEN LN 330ML',
    QTD: '6',
    UN: 'UN',
    VL_UN_R$: '5,45',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '32,70',
  },
  {
    '#': 26,
    COD: '1075',
    DESCRIÇÃO: 'PAO FRANCES kg',
    QTD: '0,59',
    UN: 'KG',
    VL_UN_R$: '12,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '7,61',
  },
  {
    '#': 27,
    COD: '3756',
    DESCRIÇÃO: 'FOLHA ALUMINIO WYDA 7,5X30',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '5,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '5,90',
  },
  {
    '#': 28,
    COD: '13664',
    DESCRIÇÃO: 'CENOURA BABY LAV MISTER RABBIT 250G',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '6,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '6,99',
  },
  {
    '#': 29,
    COD: '3892',
    DESCRIÇÃO: 'GUARDANAPO MASCOT FOLHA SIMP C/50 PQ',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '2,25',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '2,25',
  },
  {
    '#': 30,
    COD: '9199',
    DESCRIÇÃO: 'AMENDOIM PETTIZ DORI CROCANTE 150G NATURAL',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '6,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '6,99',
  },
  {
    '#': 31,
    COD: '59525',
    DESCRIÇÃO: 'QUEIJO CABRA BARRA ALHO/ERVAS 125G',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '29,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '29,90',
  },
  {
    '#': 32,
    COD: '794',
    DESCRIÇÃO: 'ABOBRINHA ITALIA kg',
    QTD: '0,515',
    UN: 'KG',
    VL_UN_R$: '9,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '5,14',
  },
  {
    '#': 33,
    COD: '827',
    DESCRIÇÃO: 'BATATA LAVADA kg',
    QTD: '0,5',
    UN: 'KG',
    VL_UN_R$: '5,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '3,00',
  },
  {
    '#': 34,
    COD: '836',
    DESCRIÇÃO: 'CEBOLA NACIONAL kg',
    QTD: '0,35',
    UN: 'KG',
    VL_UN_R$: '5,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '2,10',
  },
  {
    '#': 35,
    COD: '791',
    DESCRIÇÃO: 'LIMAO TAITI kg',
    QTD: '0,43',
    UN: 'KG',
    VL_UN_R$: '4,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '2,15',
  },
  {
    '#': 36,
    COD: '8843',
    DESCRIÇÃO: 'BERINJELA COMUM kg',
    QTD: '0,305',
    UN: 'KG',
    VL_UN_R$: '9,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '3,05',
  },
  {
    '#': 37,
    COD: '5676',
    DESCRIÇÃO: 'AGUA DE COCO KEROCOCO 1L',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '8,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '8,99',
  },
  {
    '#': 38,
    COD: '5676',
    DESCRIÇÃO: 'AGUA DE COCO KEROCOCO 1L',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '8,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '8,99',
  },
  {
    '#': 39,
    COD: '5777',
    DESCRIÇÃO: 'SUCO AURORA INT 1,5L UVA',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '13,99',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '13,99',
  },
  {
    '#': 40,
    COD: '42915',
    DESCRIÇÃO: 'QUEIJO COALHO SCALA kg',
    QTD: '0,322',
    UN: 'KG',
    VL_UN_R$: '69,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '22,51',
  },
  {
    '#': 41,
    COD: '15283',
    DESCRIÇÃO: 'PAO DE ALHO ZINHO 300G BOLINHA TRAD',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '9,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '9,90',
  },
  {
    '#': 42,
    COD: '32987',
    DESCRIÇÃO: 'PAO DE ALHO ZINHO 300G TRADICIONAL',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '9,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '9,90',
  },
  {
    '#': 43,
    COD: '57657',
    DESCRIÇÃO: 'AMAC FOFO 1,8L AZUL TRADICIONAL',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '10,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '10,90',
  },
  {
    '#': 44,
    COD: '22752',
    DESCRIÇÃO: 'GELO SO-GELO PCT 5kg',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '11,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '11,90',
  },
  {
    '#': 45,
    COD: '22752',
    DESCRIÇÃO: 'GELO SO-GELO PCT 5kg',
    QTD: '1',
    UN: 'UN',
    VL_UN_R$: '11,9',
    '(VL_TR_R$)*': null,
    VL_ITEM_R$: '11,90',
  },
];

products.forEach((p) => {
  const value =
    teste
      ?.filter((item) => item.COD == p.COD)
      ?.map((r) => r.GTIN)
      .join() || null;
  p['GTIN'] = value;
});

console.log(products);
